### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by NickWAU** [srnsw/vmbx#1]
Noting that when running on Windows 10 Enterprise (1803) with the latest version of siegfried this tool produces an error, as per the screenshot.

Any insights appreciated. An EML file is produced, although, the conversion doesn't proceed.

![VMBX](https://user-images.githubusercontent.com/74628940/99460899-d58ad700-2984-11eb-9f2b-9571bd0e0b9b.jpg)

**Comment by richardlehane** [comment]
Hi Nick
this error is coming from siegfried & I expect is because your version of siegfried is *too* up-to-date. Because the releases in this repository were made years ago, they have an older version of the siegfried library which is not compatible with current signatures.
If you have golang installed, you could do your own fresh build & that would fix it.
I'll fork this repo over the weekend and create updated releases with latest siegfried.
cheers
Richard

**Comment by NickWAU** [comment]
Thanks for responding, Richard.

If you did have a chance to look at this issue that would be fantastic. 

I'm not familiar with GoLang, although, if you didn't get to it will see what I can figure out.

Nick.

**Comment by richardlehane** [comment]
Hi Nick
I got round to it this weekend. Results at github.com/richardlehane/vmbx. I don't have access to a windows box at the moment so it is untested. Any issues please post over at that new repository

**Comment by NickWAU** [comment]
Thanks Richard,

Works perfectly! Thanks again for taking the time to look into this, very much appreciated.

Nick.
